build_variant:
  - normal
  # As of 5/30/2022 headles is only to be available on the sfe1ed40 channel
  # - headless
MACOSX_SDK_VERSION:    # [(osx and arm64)]
  - 12.3               # [(osx and arm64)]
CONDA_BUILD_SYSROOT:   # [(osx and arm64)]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk  # [(osx and arm64)]
