build_variant:
  - normal
  # As of 5/30/2022 headles is only to be available on the sfe1ed40 channel
  # - headless
MACOSX_SDK_VERSION:    # [(osx and arm64)]
  - 12.3               # [(osx and arm64)]
CONDA_BUILD_SYSROOT:   # [(osx and arm64)]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk  # [(osx and arm64)]


# As of 2024/03 -- OSX basically never had qt builds. If somebody asks, we can build them
# As of 2024/03 -- qt6 works better than qt5 on aarch64. So drop qt5.
# As of 2024/03 -- No windows users have expressed concerns about the qt libraries. don't build None
# As of 2024/05 -- We had trouble gettin the aarch64 builds to work well with Qt6 and import cv2 on the CIs.
#                  We can re-consider adding Qt6 support for Aarch upon request.
qt_version:
  - none       # [not win]
  - 5          # [not (ppc64le or aarch64 or osx)]
