# https://doc.qt.io/qt-6/windows.html
c_compiler:        # [win]
  - vs2022         # [win]
cxx_compiler:      # [win]
  - vs2022         # [win]
c_stdlib_version:  # [win]
  - 2022.12        # [win]

build_variant:
  - normal
  - headless

libabseil:
  - 20250814.1
libprotobuf:
  - 6.33.0

# Temporary pin until the global gstreamer pin is updated.
# OpenCV should be built against 1.28.1 specifically because this
# release contains the CVE fixes we want to pick up.q
gst_plugins_base:
  - '1.28.1'

gstreamer:
  - '1.28.1'
