{% set version = "4.5.4" %}
{% set use_n_python_patch = os.environ.get('OPENCV_USE_N_PYTHON_PATCH', '0') %}

package:
  name: opencv-suite
  version: {{ version }}

source:
  # - git_url: https://github.com/opencv/opencv
  #   git_tag: {{ version }}
  #   git_depth: 10
  - url: https://github.com/opencv/opencv/archive/{{ version }}.zip
  # https://github.com/opencv/opencv/archive/refs/tags/4.5.4.zip
    fn: opencv-{{ version }}.zip
    # sha256: 2c75b129da2e2c8728d168b7bf14ceca2da0ebe938557b109bae6742855ede13
    # sha256: b79ccdc4797a959c5ab17249a8a302c066248ae070e4d7010e2d77a625fdb30a
    sha256: 5deac7f7341faf4b23c38d65f8f89dbf5b4b30d345390a60853640967a2bf61b
  - url: https://github.com/opencv/opencv_contrib/archive/{{ version }}.tar.gz
    fn: opencv_contrib-{{ version }}.tar.gz
    sha256: ad74b440b4539619dc9b587995a16b691246023d45e34097c73e259f72de9f81
    folder: opencv_contrib-{{ version }}

build:
  number: 0
  # Python 2.7 is not supported on Windows
  skip: True  # [win and py27]
  script_env:
    - OPENCV_USE_N_PYTHON_PATCH

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - msinttypes            # [win and py<35]
    - ninja
    - pkg-config
  host:
    - cmake
    - eigen
    - ffmpeg
    - freetype
    - glib          #[x86_64]
    - harfbuzz              # [not win]
    - hdf5
    - jpeg
    - openjpeg
    - libpng
    - libprotobuf  =3.5.1     # [x86_64]
    - libtiff
    - libwebp
    - numpy {{ numpy }}
    - openblas-devel        # [not (ppc64le or arm64)]
    - python
    - qt =5.9.7                   # [not (osx or ppc64le or s390x)]
    - zlib
  run:
    - libgcc-ng # [not osx]
    - libstdcxx-ng # [not osx]
    - eigen                 # [not s390x]
    - ffmpeg                # [not s390x]
    - freetype
    - glib          #[x86_64]
    - gstreamer          #[x86_64]
    - gst-plugins-base          #[x86_64]
    - harfbuzz              # [not win]
    - hdf5
    - jpeg
    - openjpeg
    - libpng
    - libprotobuf =3.5.1     # [x86_64]
    - libtiff
    - libwebp
    - numpy ={{ numpy }}
    - openblas-devel        # [not (ppc64le or arm64)]
    - _openmp_mutex               # [x86_64]
    - python
    - qt  =5.9.7          # [not (osx or ppc64le or s390x)]
    - zlib


test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - python
    - numpy
  files:
    - test-cmake/CMakeLists.txt
    - test-cmake/DisplayImage.cpp
    - test.cpp
  commands:
    - pushd test-cmake
    - cmake . -DOpenCV_STATIC=OFF -DOpenCV_SHARED=ON -G"Visual Studio 14 2015"        # [win32]
    - cmake . -DOpenCV_STATIC=OFF -DOpenCV_SHARED=ON -G"Visual Studio 14 2015 Win64"  # [win64]
    - cmake . -DOpenCV_STATIC=OFF -DOpenCV_SHARED=ON                                  # [not win]
    - cmake --build . --config Release
    - popd
    # Verify dynamic libraries.
    # "bioinspired", Not working in 3.1.0
    {% set opencv_libs = [
         "aruco",
         "bgsegm",
         "calib3d",
         "ccalib",
         "core",
         "datasets",
         "dpm",
         "face",
         "features2d",
         "flann",
         "fuzzy",
         "highgui",
         "imgcodecs",
         "imgproc",
         "line_descriptor",
         "ml",
         "objdetect",
         "optflow",
         "phase_unwrapping",
         "photo",
         "plot",
         "reg",
         "rgbd",
         "saliency",
         "shape",
         "stereo",
         "stitching",
         "structured_light",
         "superres",
         "surface_matching",
         "text",
         "tracking",
         "video",
         "videoio",
         "videostab",
         "xfeatures2d",
         "ximgproc",
         "xobjdetect",
         "xphoto",
    ] %}
    {% for each_opencv_lib in opencv_libs %}
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.dylib                        # [osx]
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.so                           # [linux]
    - if not exist %PREFIX%\\Library\\bin\\opencv_{{ each_opencv_lib }}342.dll exit 1  # [win]
    {% endfor %}

about:
  home: http://opencv.org/
  license: BSD 3-clause
  license_family: BSD
  summary: Computer vision and machine learning software library.
  description: |
    OpenCV (Open Source Computer Vision Library) includes several hundreds of computer vision algorithms.
    It has a modular structure,which means that the package includes several shared or static libraries.
  doc_url: http://docs.opencv.org/
  doc_source_url: https://github.com/opencv/opencv/tree/master/doc
